### ISSUE TITLE
Build fails to find the config make file

### ISSUE THREAD

**Issue by udrawat** [CurveOS/android_device_sony_maple#2]
I followed all the steps and this is the result when trying to build: 

build/core/product_config.mk:237: *** Can not locate config makefile for product "lineage_maple_userdebug".  Stop.
Device maple_userdebug not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Repository for maple_userdebug not found in the LineageOS Github repository list. If this is in error, you may need to manually add it to your local_manifests/roomservice.xml.
build/core/product_config.mk:237: *** Can not locate config makefile for product "lineage_maple_userdebug".  Stop.
build/core/product_config.mk:237: *** Can not locate config makefile for product "lineage_maple_userdebug".  Stop.

** Don't have a product spec for: 'lineage_maple_userdebug'
** Do you have the right repo manifest?

**Comment by CurveOS** [comment]
Did you run breakfast or lunch? Breakfast is for official devices. Lunch for unofficial. The device tree isn't really working well atm. I have to solve a problem with getting lineage.mk to look for common.mk elsewhere.

**Comment by udrawat** [comment]
Thanks when will you port we are waiting developer like you plz done leave
in between

**Comment by udrawat** [comment]
Can i do anything for you?

**Comment by CurveOS** [comment]
I will port when I can make sure that all is working well. You could help me solve the issue with compilation failing to find common.mk in the right place.

**Comment by udrawat** [comment]
hey i notice one more thing every option in lunch menu is failing

**Comment by CurveOS** [comment]
So, can you help out or not?

**Comment by CurveOS** [comment]
Alright. I'm gonna have to close this one as you clearly aren't interested in helping out. When you change your mind, you're free to fork my repo and work on it and commit PR's.
